# Generated by Django 5.1.6 on 2025-03-13 13:44

import django.db.models.deletion
import fileApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=fileApp.models.customDir, verbose_name="Файл"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Название файла"
                    ),
                ),
                ("size", models.IntegerField(verbose_name="Размер файла")),
                (
                    "extensions",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Расширения файла"
                    ),
                ),
                (
                    "share_link",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Поделиться"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Комментарий"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "downloaded",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата скачивания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
