# Generated by Django 5.1.6 on 2025-03-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileApp", "0002_alter_usersfiles_options"),
        ("folderApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersfiles",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="folderApp.usersfolders",
                verbose_name="Папка",
            ),
        ),
    ]
